# Generated by Django 4.2 on 2023-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_district_name_delete_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('assembly_constituency', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='voter_lists/')),
            ],
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
